### ISSUE TITLE
user friendliness of the sozuctl tool

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#270]
we don't have it, we need it, start implementing it...

right now the tool just displays the raw JSON message that was received. We should display information in a more readable way (maybe still display the json message if we pass a `--json` flag?), especially for metrics and queries

**Comment by Geal** [comment]
current issues I see:
- there is no error when we try to remove a non existant application
- the status command will hang if a worker was killed and does not answer

**Comment by Geal** [comment]
take a look at #265 for the same concepts

**Comment by Geal** [comment]
tracking current issues related to user friendliness:

- [ ] #278: convert sozuctl to structopt
- [ ] #279: add timeouts to sozuctl commands
- [ ] #280: pretty printing sozuctl's output
- [ ] #281: add a flag to sozuctl to display the JSON data that was sent back
- [ ] #282: reorder the commands in sozuctl upgrade

**Comment by BlackYoup** [comment]
There is also no output for most of the command when the execution went fine.

For instance, there is this comment hiding all messages: https://github.com/sozu-proxy/sozu/blob/ba6a14166170c5a92c389b45032a44bd6f472a77/ctl/src/command.rs#L1107

Also, I'm in favor to display something if we try to delete a resource that don't exist but:
- should the proxy answer with a `OrderMessageStatus::Error(String::from("couldn't find xxx to delete"))` ?
- or should it answer with a `OrderMessageStatus::Ok` and a custom `data: OrderMessageAnswerData` with the "error" ?
