### ISSUE TITLE
metrics overhaul

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#404]
the metrics system is not satisfying yet, there are various issues to address right now:

- [x] #381 metrics don't get correctly reported when there are multiple workers
- [x] #401 verify the behaviour of metrics flushing
- [x] #402 check buffering behaviour of metrics 
- [x] #403 more granular response times
- [x] #405 unnecessary uses of macros
- [x] #268 do not store metrics data for old applications and instances indefinitely

**Comment by Geal** [comment]
after some discussion with @divarvel, we have an idea of how it could work.

## Constraints

We can send metrics to two outputs:

- network (statsd, influx, etc)
- local query (through the metrics configuration message)

Histograms are tricky to handle, because we currently generate them separately on each worker, and they cannot be aggregated well (there are some probabilistic algorithms for this though)

We do not need the same granularity on local and network outputs:

- network might need more specific data, like "this request for this app id on this backend got status 200 in 100 ms", but with some sampling to avoid too much traffic. In that case we wouldn't store many metrics
- local metrics could have more aggregated results, like "histogram of response times for the last hour". In that case we have to store a window of recent metrics

Cardinality is tricky too, since it can be very high for some of the metadata, like application id, backend id, domain name, client IP address.

Some of the metadata, like application ids, can take a lot of space. It might be possible to index them instead of storing them directly for each metric.

It is probably not a good idea to transmit all of the data to the master to then send to various output, as it might generate a lot of traffic between processes.

That system should not be too adherent to the master/worker system, and work correctly when we're just using the library.

We might want to make the raw metrics available as part of a future event notification system: https://github.com/sozu-proxy/sozu/issues/261

## Proposal

We have two (maybe more in the future?) systems that want access to all the metrics, but will not store or send them in the same way.
We can have them work as subscribers to the metrics:
- network output:
  - receives all the metrics
  - updates instant values, like gauges or counters
  - stores histogram metrics (like response times) in a queue
  - whenever its `write()` method is called, outputs the instant values (maybe resetting the counters), and sends the response times as well
  - we can easily reduce the traffic for instant values, with a setting like "do not send this metric again unless a second has passed" (current system works like that)
  - for response times, I do not know yet how sampling might work, but we'll find a way
- local (configuration query) output:
  - receives all the metrics
  - updates instant values, like gauges or counters
  - stores all the response times for the previous hour
  - whenever it gets a query message, send all the instant values, reset the counters, and calculate response time histograms for the last minute and last hour. Globally and per application id too?
  - its main usage should be in regular polling from external tools. Potential issue here: what happens if multiple clients ask for the metrics? Potential solution: generate the report regularly, and when the clients ask, give the latest report

The local query system might be too costly (in terms of storage, and also in generating the histograms) if we have a lot of traffic, so either we have a way to sample the data, or we must be able to deactivate it if needed

**Comment by Geal** [comment]
done with the metrics rewrite 73aa805 to 3ea91fe
