### ISSUE TITLE
Get cluster metrics

### ISSUE THREAD

**Issue by Keksoj** [sozu-proxy/sozu#789]
The pull request #783 restores the querying of proxy metrics (`accept_queue`, `http_responses`, `event_loop_time`…), but leaves this problems: 

- Querying cluster metrics returns nothing.
- Querying a list of metric names with `query metrics -l` returns no cluster metric names

## Todo

- [x] investigate wether cluster metrics are stored at all
- [x] return them to the CLI
- [x] fix `dump_cluster_data()` probably
