### ISSUE TITLE
Create a pulsar connector to receive commands

### ISSUE THREAD

**Issue by Keksoj** [sozu-proxy/sozu#878]
For the needs of the Clever Cloud architecture, it would be handy to have a CLI command of this form:

```
sozu connector pulsar --topic <TOPIC> --token <TOKEN>
```

that spawns a pulsar connector, which, in essence:

1. has a pulsar client listening on this topic
2. receives commands and parses them
3. writes the commands on the local unix socket (like the CLI does) for the main process to receive

Did I get this right @FlorentinDUBOIS ?

## Todos

- [ ] choose a milestone for this issue
- [ ] create a CLI command to start the connector
- [ ] create a pulsar client 
- [ ] parse commands
- [ ] write the commands on the unix socket
- [ ] test

**Comment by FlorentinDUBOIS** [comment]
Yes 👏, this is the base idea of this feature 🙂. I will add details about the milestone and others stuffs in this issue.

**Comment by Geal** [comment]
If it is specific to the Clever Cloud architecture, shouldn't this live in another project? Because the Pulsar client is likely to add a lot of new code and dependencies for all users.

If it is meant for use outside of clever, could we discuss the message format? I kind of remember that we wanted to change it while I was still there, it might be the right time to design config messages that are compelling for more users

**Comment by FlorentinDUBOIS** [comment]
It is not specific to Clever Cloud, the idea is to provide a sidecar as sozu that listen to pulsar and pipe [command](https://github.com/sozu-proxy/sozu/tree/main/command) messages to the socket, nothing more to me. 

I remember that we spoke about the updating the message format to provide some extra tooling. One example was the Protobuf format that will allow to generate structures and services in multiple languages. This could be used to create gRPC sidecar to interact with Sōzu. Is that this that you have in mind?

**Comment by FlorentinDUBOIS** [comment]
I forgot that I agree that we need a compiler feature flag for enabling the `connector` feature.

**Comment by Geal** [comment]
It could make sense to check grpc now yes, there's way better support in rust than before.
The issue with adding pulsar is that soon you'll have to add more protocols, like AMQP or kafka, and if they all end up in the main sozu binary, that  becomes unmanageable: lots of dependencies and a release cycle that may have to follow them.
As a separate binary that brings in the command lib and pulsar, that makes a lot more sense and that would be easier to evolve independently. That was the goal of releasing the command lib, more tools can use it

**Comment by Keksoj** [comment]
After bootstrapping the pulsar client in the `main` workspace and then in its own `pulsar` workspace, I'm growing fond of the idea of putting the pulsar connector in its own repository:

- it needs a bunch of heavy dependencies: Pulsar, Tokio…
- all it needs from Sōzu is the command lib and the path to the unix socket

So we could imagine a binary that runs this way:

```
pulsar-connector --topic <TOPIC> --token <TOKEN> --config <PATH_TO_CONFIG.TOML>
```

Parsing `config.toml` to find this line:

```toml
command_socket = "./sozu.sock"
```

And we're good to go.

**Comment by Geal** [comment]
Also the command lib gives you all you need for state management, like getting the current config from sozu, making a diff, generating events, etc

**Comment by Keksoj** [comment]
The pulsar connector has been created in this repo:

https://github.com/CleverCloud/sozu-pulsar-connector
